services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  bar_tender:
    image: bar_tender
    container_name: bar_tender-container
    restart: always
    depends_on:
      - mongodb
    env_file:
      - dockerEnvironmentVariables.env
    ports:
      - "6969:6969"

volumes:
  mongo-data:
    driver: local
