from enum import Enum

class MongoDBConfigFields(Enum):
    HOST = "HOST"
    PORT = "PORT"
    USERNAME = "USERNAME"
    PASSWORD = "PASSWORD"
    DATABASE_NAME = "DATABASE_NAME"
    PUMP_COLLECTION_NAME = "PUMP_COLLECTION_NAME"
    GLAS_COLLECTION_NAME = "GLAS_COLLECTION_NAME"
    INGREDIENTS_COLLECTION_NAME = "INGREDIENTS_COLLECTION_NAME"
    RECIPE_COLLECTION_NAME = "RECIPE_COLLECTION_NAME"